In [1]:
import numpy as np
import pandas as pd
from sklearn import datasets
iris = datasets.load_iris()

In [2]:
Xsl = iris["data"][:, 0:1]  # sepal length array
Xsw = iris["data"][:, 1:2]  # sepal width array
Xpl = iris["data"][:, 2:3]  # petal length array
Xpw = iris["data"][:, 3:]  # petal width array
y = iris.target

"You normalize your data in another table"

In [3]:
sl_norm = (Xsl - Xsl.min())/ (Xsl.max() - Xsl.min())
new_sl = (4.8 - Xsl.min())/ (Xsl.max() - Xsl.min())

sw_norm = (Xsw - Xsw.min())/ (Xsw.max() - Xsw.min())
new_sw = (2.5 - Xsw.min())/ (Xsw.max() - Xsw.min())

pl_norm = (Xpl - Xpl.min())/ (Xpl.max() - Xpl.min())
new_pl = (5.3 - Xpl.min())/ (Xpl.max() - Xpl.min())

pw_norm = (Xpw - Xpw.min())/ (Xpw.max() - Xpw.min())
new_pw = (2.4 - Xpw.min())/ (Xpw.max() - Xpw.min())

"You code a simple euclid distance function"

und

"You take a point and calculate the distance to all points"

In [4]:
distances_sl = np.linalg.norm(sl_norm - new_sl, axis=1)

distances_sw = np.linalg.norm(sw_norm - new_sw, axis=1)

distances_pl = np.linalg.norm(pl_norm - new_pl, axis=1)

distances_pw = np.linalg.norm(pw_norm - new_pw, axis=1)

"You take the list from above and sort it"

In [5]:
k = 10
nearest_neighbor_ids_sl = distances_sl.argsort()[:k]
nearest_neighbor_ids_sl

array([ 30,  45,  12,  11,  24,   2,  29,   9,  57, 106])

In [6]:
nearest_neighbor_ids_sw = distances_sw.argsort()[:k]
nearest_neighbor_ids_sw

array([ 72, 108, 106, 113,  98,  69, 146,  89,  90, 134])

In [7]:
nearest_neighbor_ids_pl = distances_pl.argsort()[:k]
nearest_neighbor_ids_pl

array([115, 111, 147, 145, 139, 148, 133, 101, 116, 137])

In [8]:
nearest_neighbor_ids_pw = distances_pw.argsort()[:k]
nearest_neighbor_ids_pw

array([136, 114, 140, 120, 118, 135, 145, 143, 141, 115])

"You take the max to determine the target class"

In [9]:
nearest_neighbor_flowers_sl = y[nearest_neighbor_ids_sl]
nearest_neighbor_flowers_sl

array([0, 0, 0, 0, 0, 0, 0, 0, 1, 2])

In [10]:
nearest_neighbor_flowers_sw = y[nearest_neighbor_ids_sw]
nearest_neighbor_flowers_sw

array([1, 2, 2, 2, 1, 1, 2, 1, 1, 2])

In [11]:
nearest_neighbor_flowers_pl = y[nearest_neighbor_ids_pl]
nearest_neighbor_flowers_pl

array([2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [12]:
nearest_neighbor_flowers_pw = y[nearest_neighbor_ids_pw]
nearest_neighbor_flowers_pw

array([2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

Genau wie bei der LogisticRegression Aufgabe ist diese Pflanze laut dem Sepal eher keine Iris-virginica (definitiv nicht laut length, eventuell laut width), aber nach dem Petal definitiv eine Iris-virginica (laut length und width).

Im Gegensatz zur LogisticRegression scheint es hier aber wahrscheinlicher, dass es eine Iris-virginica ist, da 2.5/4 Werten dafür sprechen. Schlüssig ist dies aber bei beiden Methoden nicht.